-- CreateTable
CREATE TABLE "URL_BATCH" (
    "BAT_ID" SERIAL NOT NULL,
    "BAT_FileName" TEXT NOT NULL,
    "BAT_FileType" TEXT NOT NULL,
    "BAT_TotalURLs" INTEGER NOT NULL DEFAULT 0,
    "BAT_Status" TEXT NOT NULL DEFAULT 'PENDING',
    "BAT_UploadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "URL_BATCH_pkey" PRIMARY KEY ("BAT_ID")
);

-- CreateTable
CREATE TABLE "URL" (
    "URL_ID" SERIAL NOT NULL,
    "URL_Original" TEXT NOT NULL,
    "URL_Normalized" TEXT NOT NULL,
    "URL_IsDuplicate" BOOLEAN NOT NULL DEFAULT false,
    "URL_CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "URL_BATCH_BAT_ID" INTEGER NOT NULL,

    CONSTRAINT "URL_pkey" PRIMARY KEY ("URL_ID")
);

-- CreateTable
CREATE TABLE "SCAN_JOB" (
    "SCN_ID" SERIAL NOT NULL,
    "SCN_Status" TEXT NOT NULL DEFAULT 'QUEUED',
    "SCN_StartedAt" TIMESTAMP(3),
    "SCN_CompletedAt" TIMESTAMP(3),
    "SCN_TotalURLs" INTEGER NOT NULL,
    "SCN_CreatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "URL_BATCH_BAT_ID" INTEGER NOT NULL,

    CONSTRAINT "SCAN_JOB_pkey" PRIMARY KEY ("SCN_ID")
);

-- CreateTable
CREATE TABLE "SCAN_RESULT" (
    "RES_ID" SERIAL NOT NULL,
    "RES_HTTPStatus" INTEGER,
    "RES_StatusLabel" TEXT,
    "RES_FinalURL" TEXT,
    "RES_RedirectCount" INTEGER NOT NULL DEFAULT 0,
    "RES_ErrorType" TEXT,
    "RES_CheckedAt" TIMESTAMP(3),
    "SCAN_JOB_SCN_ID" INTEGER NOT NULL,
    "URL_URL_ID" INTEGER NOT NULL,

    CONSTRAINT "SCAN_RESULT_pkey" PRIMARY KEY ("RES_ID")
);

-- CreateIndex
CREATE INDEX "URL_URL_BATCH_BAT_ID_idx" ON "URL"("URL_BATCH_BAT_ID");

-- CreateIndex
CREATE INDEX "URL_URL_Normalized_idx" ON "URL"("URL_Normalized");

-- CreateIndex
CREATE INDEX "SCAN_RESULT_SCAN_JOB_SCN_ID_idx" ON "SCAN_RESULT"("SCAN_JOB_SCN_ID");

-- CreateIndex
CREATE INDEX "SCAN_RESULT_URL_URL_ID_idx" ON "SCAN_RESULT"("URL_URL_ID");

-- AddForeignKey
ALTER TABLE "URL" ADD CONSTRAINT "URL_URL_BATCH_BAT_ID_fkey" FOREIGN KEY ("URL_BATCH_BAT_ID") REFERENCES "URL_BATCH"("BAT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCAN_JOB" ADD CONSTRAINT "SCAN_JOB_URL_BATCH_BAT_ID_fkey" FOREIGN KEY ("URL_BATCH_BAT_ID") REFERENCES "URL_BATCH"("BAT_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCAN_RESULT" ADD CONSTRAINT "SCAN_RESULT_SCAN_JOB_SCN_ID_fkey" FOREIGN KEY ("SCAN_JOB_SCN_ID") REFERENCES "SCAN_JOB"("SCN_ID") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SCAN_RESULT" ADD CONSTRAINT "SCAN_RESULT_URL_URL_ID_fkey" FOREIGN KEY ("URL_URL_ID") REFERENCES "URL"("URL_ID") ON DELETE RESTRICT ON UPDATE CASCADE;
