import { useEffect, useState } from "react";

import {
  AlertTriangle,
  CheckCircle2,
  Clock,
  ExternalLink,
  History,
  Link2,
  RefreshCw,
  Search,
} from "lucide-react";

import { getJobResults } from "../services/api";

function ScanResults({ jobId, onJobChange }) {
  const [job, setJob] = useState(null);
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [jobIdInput, setJobIdInput] = useState("");

  useEffect(() => {
    if (!jobId) {
      setJob(null);
      setResults([]);
      setLoading(false);
      setError("");
      return;
    }

    let intervalId;
    let cancelled = false;

    async function loadResults() {
      try {
        const data = await getJobResults(jobId);

        if (cancelled) {
          return;
        }

        setJob(data);
        setResults(data.results || []);
        setError("");

        if (data.status === "COMPLETED") {
          clearInterval(intervalId);
        }
      } catch (err) {
        if (!cancelled) {
          setError(
            err.message || "Failed to load scan results."
          );
        }
      } finally {
        if (!cancelled) {
          setLoading(false);
        }
      }
    }

    setLoading(true);
    setError("");

    loadResults();

    intervalId = setInterval(() => {
      loadResults();
    }, 1000);

    return () => {
      cancelled = true;
      clearInterval(intervalId);
    };
  }, [jobId]);

  function handleViewJob(event) {
    event.preventDefault();

    const parsedJobId = Number(jobIdInput);

    if (!Number.isInteger(parsedJobId) || parsedJobId <= 0) {
      setError("Enter a valid Job ID.");
      return;
    }

    setError("");
    onJobChange(parsedJobId);
  }

  const operationalCount = results.filter(
    (result) => result.statusLabel === "OPERATIONAL"
  ).length;

  const issueCount = results.filter(
    (result) =>
      result.statusLabel &&
      result.statusLabel !== "OPERATIONAL"
  ).length;

  return (
    <div className="content-wrap">
      <section className="page-heading">
        <div>
          <span className="section-kicker">
            URL VALIDATION
          </span>

          <h1>Scan Results</h1>

          <p>
            Review current and previous URL validation results
            generated by TraceLink.
          </p>
        </div>
      </section>

      <section className="panel full-panel">
        <div className="panel-heading">
          <div>
            <span className="section-kicker">
              SCAN HISTORY
            </span>

            <h2>View Previous Scan</h2>

            <p className="panel-subtitle">
              Enter a Job ID to retrieve the results of a previous
              batch scan.
            </p>
          </div>

          <History size={20} />
        </div>

        <form onSubmit={handleViewJob}>
          <div className="job-search">
            <input
              type="number"
              min="1"
              placeholder="Enter Job ID"
              value={jobIdInput}
              onChange={(event) =>
                setJobIdInput(event.target.value)
              }
            />

            <button
              type="submit"
              className="button button-primary"
            >
              <Search size={16} />
              View Results
            </button>
          </div>
        </form>
      </section>

      {loading && !job && (
        <section className="panel full-panel">
          <div className="empty-state">
            <RefreshCw size={32} />

            <h3>Loading scan results...</h3>

            <p>
              Retrieving URL validation results from TraceLink.
            </p>
          </div>
        </section>
      )}

      {error && (
        <section className="panel full-panel">
          <div className="empty-state">
            <AlertTriangle size={32} />

            <h3>Unable to load scan results</h3>

            <p>{error}</p>
          </div>
        </section>
      )}

      {!jobId && !loading && (
        <section className="panel full-panel">
          <div className="empty-state">
            <Link2 size={32} />

            <h3>No scan selected</h3>

            <p>
              Start a new batch scan or enter a Job ID above to
              review previous results.
            </p>
          </div>
        </section>
      )}

      {job && (
        <>
          <section className="stats-grid">
            <div className="metric-card">
              <div className="metric-top">
                <span>Total URLs</span>

                <span className="metric-icon cyan">
                  <Link2 size={16} />
                </span>
              </div>

              <div className="metric-value">
                {job.totalUrls ?? 0}
              </div>

              <div className="metric-detail">
                URLs in this scan
              </div>
            </div>

            <div className="metric-card">
              <div className="metric-top">
                <span>Operational</span>

                <span className="metric-icon green">
                  <CheckCircle2 size={16} />
                </span>
              </div>

              <div className="metric-value">
                {operationalCount}
              </div>

              <div className="metric-detail">
                Successfully validated
              </div>
            </div>

            <div className="metric-card">
              <div className="metric-top">
                <span>Issues</span>

                <span className="metric-icon coral">
                  <AlertTriangle size={16} />
                </span>
              </div>

              <div className="metric-value">
                {issueCount}
              </div>

              <div className="metric-detail">
                Non-operational results
              </div>
            </div>

            <div className="metric-card">
              <div className="metric-top">
                <span>Status</span>

                <span className="metric-icon amber">
                  <Clock size={16} />
                </span>
              </div>

              <div className="metric-value">
                {job.status ?? "UNKNOWN"}
              </div>

              <div className="metric-detail">
                Current scan status
              </div>
            </div>
          </section>

          <section className="panel full-panel">
            <div className="panel-heading">
              <div>
                <span className="section-kicker">
                  SCAN INFORMATION
                </span>

                <h2>Batch Details</h2>

                <p className="panel-subtitle">
                  Information associated with this scan job.
                </p>
              </div>
            </div>

            <div className="scan-information">
              <div>
                <span>Job ID: </span>
                <strong>{job.jobId ?? "—"}</strong>
              </div>

              <div>
                <span>Batch ID: </span>
                <strong>{job.batchId ?? "—"}</strong>
              </div>

              <div>
                <span>File: </span>
                <strong>{job.fileName ?? "—"}</strong>
              </div>

              <div>
                <span>Processed: </span>
                <strong>
                  {results.length} / {job.totalUrls ?? 0}
                </strong>
              </div>
            </div>
          </section>

          <section className="panel full-panel results-panel">
            <div className="panel-heading scan-table-heading">
              <div>
                <span className="section-kicker">
                  URL RESULTS
                </span>

                <h2>Technical Validation Results</h2>

                <p className="panel-subtitle">
                  HTTP status, redirects, duplicates, and errors
                  detected during the scan.
                </p>
              </div>

              {job.status === "PROCESSING" && (
                <div className="scan-status">
                  <RefreshCw size={16} />
                  Processing
                </div>
              )}
            </div>

            {results.length === 0 ? (
              <div className="empty-state">
                <Clock size={28} />

                <h3>No results available yet</h3>

                <p>
                  Results will appear as URLs are processed.
                </p>
              </div>
            ) : (
              <div className="table-scroll">
                <table className="results-table">
                  <thead>
                    <tr>
                      <th>Original URL</th>
                      <th>HTTP</th>
                      <th>Status</th>
                      <th>Final URL</th>
                      <th>Redirects</th>
                      <th>Duplicate</th>
                      <th>Error</th>
                      <th>Checked At</th>
                    </tr>
                  </thead>

                  <tbody>
                    {results.map((result) => (
                      <tr key={result.resultId}>
                        <td>
                          <div className="url-cell">
                            <a
                              href={result.url?.original}
                              target="_blank"
                              rel="noreferrer"
                            >
                              {result.url?.original ?? "—"}
                              <ExternalLink size={13} />
                            </a>
                          </div>
                        </td>

                        <td>
                          <span className="http-code">
                            {result.httpStatus ?? "—"}
                          </span>
                        </td>

                        <td>
                          <span
                            className={`status-tag ${
                              result.statusLabel
                                ? result.statusLabel.toLowerCase()
                                : ""
                            }`}
                          >
                            {result.statusLabel ?? "UNKNOWN"}
                          </span>
                        </td>

                        <td>
                          {result.finalUrl ? (
                            <div className="url-cell">
                              <a
                                href={result.finalUrl}
                                target="_blank"
                                rel="noreferrer"
                              >
                                {result.finalUrl}
                                <ExternalLink size={13} />
                              </a>
                            </div>
                          ) : (
                            "—"
                          )}
                        </td>

                        <td>
                          {result.redirectCount ?? 0}
                        </td>

                        <td>
                          {result.url?.isDuplicate
                            ? "Yes"
                            : "No"}
                        </td>

                        <td>
                          {result.errorType ?? "—"}
                        </td>

                        <td>
                          {result.checkedAt
                            ? new Date(
                                result.checkedAt
                              ).toLocaleString()
                            : "—"}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            )}
          </section>
        </>
      )}
    </div>
  );
}

export default ScanResults;